CREATE TABLE quizzes (
  quiz_id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  cover_image_url VARCHAR(500),
  subject_id INT NOT NULL REFERENCES subjects(subject_id),
  topic_id INT REFERENCES topics(topic_id) ON DELETE SET NULL,
  category_id INT REFERENCES quiz_categories(category_id) ON DELETE SET NULL,
  difficulty_level VARCHAR(20) DEFAULT 'medium' CHECK (difficulty_level IN ('easy', 'medium', 'hard')),
  creator_id INT NOT NULL REFERENCES users(user_id),
  access_level VARCHAR(20) DEFAULT 'draft' CHECK (access_level IN ('draft', 'private', 'class', 'public')),
  total_score DECIMAL(5,2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);
